In [1]:
import numpy as np

In [2]:
my_array= np.array([1,3,5,7,9,2,4,6,8,3,34,5,-2,34])

In [3]:
print(f"The mean is {my_array.mean()}")
print(f"The sd is {my_array.std()}")
print(f"Multiplication by 2: {my_array*2}")

The mean is 8.5
The sd is 10.768671492541952
Multiplication by 2: [ 2  6 10 14 18  4  8 12 16  6 68 10 -4 68]


In [4]:
my_arr_4x3=np.array([[1,2,3], [4,5,6,],[7,8,9],[10,11,12]]) #bi-dimensional array to create a matrix
my_arr_4x3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
print(f"Inverted matrix: \n{my_arr_4x3.T}") #it inverts the array, with .T

Inverted matrix: 
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [5]:
my_arr_4x3 * 4

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36],
       [40, 44, 48]])

In [7]:
print(f"Elements in this matrix:{my_arr_4x3.size}")

Elements in this matrix:12


In [8]:
print(f"Shape of this matrix:{my_arr_4x3.shape}")

Shape of this matrix:(4, 3)


In [9]:
np.random.randint(100,200)  #generates a random number between the 2 parameters

136

In [11]:
random_int=np.random.randint(100,200,20) #generates an array of numbers with a step of 20

In [13]:
random_int%2 #list to find if even or odd 0=even 1=odd

array([1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1],
      dtype=int32)

In [16]:
even_numb=random_int[random_int%2 ==0] #take only the even numbers who mathces the condition
print(even_numb)

[188 158 192 152 116 144 138 154 136 158]


In [19]:
even_numb[2:8] #take only the numbers between the 2 positions

array([192, 152, 116, 144, 138, 154], dtype=int32)

In [24]:
arr1=np.random.randint(0,10,4)
arr2=np.random.randint(0,10,4)
print(f"The two arrays are:\n{arr1}\n{arr2}")

The two arrays are:
[8 2 9 5]
[2 6 3 6]


In [27]:
print(f"The sum of the two arrays is \n{arr1}+{arr2}={arr1+arr2}")
print(f"The Multiplication of the two arrays is \n{arr1}*{arr2}={arr1*arr2}")

The sum of the two arrays is 
[8 2 9 5]+[2 6 3 6]=[10  8 12 11]
The Multiplication of the two arrays is 
[8 2 9 5]*[2 6 3 6]=[16 12 27 30]


In [28]:
np.dot(arr1,arr2) #iot gives the total product of the two arrays

np.int32(85)